/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as protectedRouteRouteImport } from './routes/(protected)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiModelsRouteImport } from './routes/api/models'
import { Route as publicAuthRouteImport } from './routes/(public)/auth'
import { Route as protectedDashboardRouteImport } from './routes/(protected)/dashboard'
import { Route as publicDocsRouteRouteImport } from './routes/(public)/docs/route'
import { Route as protectedSettingsRouteRouteImport } from './routes/(protected)/settings/route'
import { Route as protectedChatsRouteRouteImport } from './routes/(protected)/chats/route'
import { Route as protectedSettingsIndexRouteImport } from './routes/(protected)/settings/index'
import { Route as protectedChatsIndexRouteImport } from './routes/(protected)/chats/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as publicDocsSplatRouteImport } from './routes/(public)/docs/$'
import { Route as protectedChatsChatIdRouteImport } from './routes/(protected)/chats/$chatId'
import { Route as protectedSettingsOrganizationRouteRouteImport } from './routes/(protected)/settings/organization/route'
import { Route as protectedSettingsOrgRouteRouteImport } from './routes/(protected)/settings/org/route'
import { Route as protectedSettingsOrganizationIndexRouteImport } from './routes/(protected)/settings/organization/index'
import { Route as protectedSettingsOrgIndexRouteImport } from './routes/(protected)/settings/org/index'
import { Route as protectedSettingsOrganizationTeamsRouteImport } from './routes/(protected)/settings/organization/teams'
import { Route as protectedSettingsOrganizationMembersRouteImport } from './routes/(protected)/settings/organization/members'
import { Route as protectedSettingsOrgAttachmentsRouteImport } from './routes/(protected)/settings/org/attachments'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedRouteRoute = protectedRouteRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsRoute = ApiModelsRouteImport.update({
  id: '/api/models',
  path: '/api/models',
  getParentRoute: () => rootRouteImport,
} as any)
const publicAuthRoute = publicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedDashboardRoute = protectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => protectedRouteRoute,
} as any)
const publicDocsRouteRoute = publicDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => publicRouteRoute,
} as any)
const protectedSettingsRouteRoute = protectedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedChatsRouteRoute = protectedChatsRouteRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => protectedRouteRoute,
} as any)
const protectedSettingsIndexRoute = protectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedSettingsRouteRoute,
} as any)
const protectedChatsIndexRoute = protectedChatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedChatsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const publicDocsSplatRoute = publicDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => publicDocsRouteRoute,
} as any)
const protectedChatsChatIdRoute = protectedChatsChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => protectedChatsRouteRoute,
} as any)
const protectedSettingsOrganizationRouteRoute =
  protectedSettingsOrganizationRouteRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsOrgRouteRoute =
  protectedSettingsOrgRouteRouteImport.update({
    id: '/org',
    path: '/org',
    getParentRoute: () => protectedSettingsRouteRoute,
  } as any)
const protectedSettingsOrganizationIndexRoute =
  protectedSettingsOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedSettingsOrganizationRouteRoute,
  } as any)
const protectedSettingsOrgIndexRoute =
  protectedSettingsOrgIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => protectedSettingsOrgRouteRoute,
  } as any)
const protectedSettingsOrganizationTeamsRoute =
  protectedSettingsOrganizationTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => protectedSettingsOrganizationRouteRoute,
  } as any)
const protectedSettingsOrganizationMembersRoute =
  protectedSettingsOrganizationMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => protectedSettingsOrganizationRouteRoute,
  } as any)
const protectedSettingsOrgAttachmentsRoute =
  protectedSettingsOrgAttachmentsRouteImport.update({
    id: '/attachments',
    path: '/attachments',
    getParentRoute: () => protectedSettingsOrgRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/chats': typeof protectedChatsRouteRouteWithChildren
  '/settings': typeof protectedSettingsRouteRouteWithChildren
  '/docs': typeof publicDocsRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRoute
  '/auth': typeof publicAuthRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/': typeof publicIndexRoute
  '/settings/org': typeof protectedSettingsOrgRouteRouteWithChildren
  '/settings/organization': typeof protectedSettingsOrganizationRouteRouteWithChildren
  '/chats/$chatId': typeof protectedChatsChatIdRoute
  '/docs/$': typeof publicDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chats/': typeof protectedChatsIndexRoute
  '/settings/': typeof protectedSettingsIndexRoute
  '/settings/org/attachments': typeof protectedSettingsOrgAttachmentsRoute
  '/settings/organization/members': typeof protectedSettingsOrganizationMembersRoute
  '/settings/organization/teams': typeof protectedSettingsOrganizationTeamsRoute
  '/settings/org/': typeof protectedSettingsOrgIndexRoute
  '/settings/organization/': typeof protectedSettingsOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/docs': typeof publicDocsRouteRouteWithChildren
  '/dashboard': typeof protectedDashboardRoute
  '/auth': typeof publicAuthRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/': typeof publicIndexRoute
  '/chats/$chatId': typeof protectedChatsChatIdRoute
  '/docs/$': typeof publicDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chats': typeof protectedChatsIndexRoute
  '/settings': typeof protectedSettingsIndexRoute
  '/settings/org/attachments': typeof protectedSettingsOrgAttachmentsRoute
  '/settings/organization/members': typeof protectedSettingsOrganizationMembersRoute
  '/settings/organization/teams': typeof protectedSettingsOrganizationTeamsRoute
  '/settings/org': typeof protectedSettingsOrgIndexRoute
  '/settings/organization': typeof protectedSettingsOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(protected)': typeof protectedRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(protected)/chats': typeof protectedChatsRouteRouteWithChildren
  '/(protected)/settings': typeof protectedSettingsRouteRouteWithChildren
  '/(public)/docs': typeof publicDocsRouteRouteWithChildren
  '/(protected)/dashboard': typeof protectedDashboardRoute
  '/(public)/auth': typeof publicAuthRoute
  '/api/models': typeof ApiModelsRoute
  '/api/search': typeof ApiSearchRoute
  '/(public)/': typeof publicIndexRoute
  '/(protected)/settings/org': typeof protectedSettingsOrgRouteRouteWithChildren
  '/(protected)/settings/organization': typeof protectedSettingsOrganizationRouteRouteWithChildren
  '/(protected)/chats/$chatId': typeof protectedChatsChatIdRoute
  '/(public)/docs/$': typeof publicDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(protected)/chats/': typeof protectedChatsIndexRoute
  '/(protected)/settings/': typeof protectedSettingsIndexRoute
  '/(protected)/settings/org/attachments': typeof protectedSettingsOrgAttachmentsRoute
  '/(protected)/settings/organization/members': typeof protectedSettingsOrganizationMembersRoute
  '/(protected)/settings/organization/teams': typeof protectedSettingsOrganizationTeamsRoute
  '/(protected)/settings/org/': typeof protectedSettingsOrgIndexRoute
  '/(protected)/settings/organization/': typeof protectedSettingsOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chats'
    | '/settings'
    | '/docs'
    | '/dashboard'
    | '/auth'
    | '/api/models'
    | '/api/search'
    | '/'
    | '/settings/org'
    | '/settings/organization'
    | '/chats/$chatId'
    | '/docs/$'
    | '/api/auth/$'
    | '/chats/'
    | '/settings/'
    | '/settings/org/attachments'
    | '/settings/organization/members'
    | '/settings/organization/teams'
    | '/settings/org/'
    | '/settings/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/docs'
    | '/dashboard'
    | '/auth'
    | '/api/models'
    | '/api/search'
    | '/'
    | '/chats/$chatId'
    | '/docs/$'
    | '/api/auth/$'
    | '/chats'
    | '/settings'
    | '/settings/org/attachments'
    | '/settings/organization/members'
    | '/settings/organization/teams'
    | '/settings/org'
    | '/settings/organization'
  id:
    | '__root__'
    | '/(protected)'
    | '/(public)'
    | '/(protected)/chats'
    | '/(protected)/settings'
    | '/(public)/docs'
    | '/(protected)/dashboard'
    | '/(public)/auth'
    | '/api/models'
    | '/api/search'
    | '/(public)/'
    | '/(protected)/settings/org'
    | '/(protected)/settings/organization'
    | '/(protected)/chats/$chatId'
    | '/(public)/docs/$'
    | '/api/auth/$'
    | '/(protected)/chats/'
    | '/(protected)/settings/'
    | '/(protected)/settings/org/attachments'
    | '/(protected)/settings/organization/members'
    | '/(protected)/settings/organization/teams'
    | '/(protected)/settings/org/'
    | '/(protected)/settings/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  protectedRouteRoute: typeof protectedRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  ApiModelsRoute: typeof ApiModelsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models': {
      id: '/api/models'
      path: '/api/models'
      fullPath: '/api/models'
      preLoaderRoute: typeof ApiModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/auth': {
      id: '/(public)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof publicAuthRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/dashboard': {
      id: '/(protected)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedDashboardRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(public)/docs': {
      id: '/(public)/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof publicDocsRouteRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(protected)/settings': {
      id: '/(protected)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedSettingsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/chats': {
      id: '/(protected)/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof protectedChatsRouteRouteImport
      parentRoute: typeof protectedRouteRoute
    }
    '/(protected)/settings/': {
      id: '/(protected)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof protectedSettingsIndexRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/chats/': {
      id: '/(protected)/chats/'
      path: '/'
      fullPath: '/chats/'
      preLoaderRoute: typeof protectedChatsIndexRouteImport
      parentRoute: typeof protectedChatsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/docs/$': {
      id: '/(public)/docs/$'
      path: '/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof publicDocsSplatRouteImport
      parentRoute: typeof publicDocsRouteRoute
    }
    '/(protected)/chats/$chatId': {
      id: '/(protected)/chats/$chatId'
      path: '/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof protectedChatsChatIdRouteImport
      parentRoute: typeof protectedChatsRouteRoute
    }
    '/(protected)/settings/organization': {
      id: '/(protected)/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof protectedSettingsOrganizationRouteRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/org': {
      id: '/(protected)/settings/org'
      path: '/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof protectedSettingsOrgRouteRouteImport
      parentRoute: typeof protectedSettingsRouteRoute
    }
    '/(protected)/settings/organization/': {
      id: '/(protected)/settings/organization/'
      path: '/'
      fullPath: '/settings/organization/'
      preLoaderRoute: typeof protectedSettingsOrganizationIndexRouteImport
      parentRoute: typeof protectedSettingsOrganizationRouteRoute
    }
    '/(protected)/settings/org/': {
      id: '/(protected)/settings/org/'
      path: '/'
      fullPath: '/settings/org/'
      preLoaderRoute: typeof protectedSettingsOrgIndexRouteImport
      parentRoute: typeof protectedSettingsOrgRouteRoute
    }
    '/(protected)/settings/organization/teams': {
      id: '/(protected)/settings/organization/teams'
      path: '/teams'
      fullPath: '/settings/organization/teams'
      preLoaderRoute: typeof protectedSettingsOrganizationTeamsRouteImport
      parentRoute: typeof protectedSettingsOrganizationRouteRoute
    }
    '/(protected)/settings/organization/members': {
      id: '/(protected)/settings/organization/members'
      path: '/members'
      fullPath: '/settings/organization/members'
      preLoaderRoute: typeof protectedSettingsOrganizationMembersRouteImport
      parentRoute: typeof protectedSettingsOrganizationRouteRoute
    }
    '/(protected)/settings/org/attachments': {
      id: '/(protected)/settings/org/attachments'
      path: '/attachments'
      fullPath: '/settings/org/attachments'
      preLoaderRoute: typeof protectedSettingsOrgAttachmentsRouteImport
      parentRoute: typeof protectedSettingsOrgRouteRoute
    }
  }
}

interface protectedChatsRouteRouteChildren {
  protectedChatsChatIdRoute: typeof protectedChatsChatIdRoute
  protectedChatsIndexRoute: typeof protectedChatsIndexRoute
}

const protectedChatsRouteRouteChildren: protectedChatsRouteRouteChildren = {
  protectedChatsChatIdRoute: protectedChatsChatIdRoute,
  protectedChatsIndexRoute: protectedChatsIndexRoute,
}

const protectedChatsRouteRouteWithChildren =
  protectedChatsRouteRoute._addFileChildren(protectedChatsRouteRouteChildren)

interface protectedSettingsOrgRouteRouteChildren {
  protectedSettingsOrgAttachmentsRoute: typeof protectedSettingsOrgAttachmentsRoute
  protectedSettingsOrgIndexRoute: typeof protectedSettingsOrgIndexRoute
}

const protectedSettingsOrgRouteRouteChildren: protectedSettingsOrgRouteRouteChildren =
  {
    protectedSettingsOrgAttachmentsRoute: protectedSettingsOrgAttachmentsRoute,
    protectedSettingsOrgIndexRoute: protectedSettingsOrgIndexRoute,
  }

const protectedSettingsOrgRouteRouteWithChildren =
  protectedSettingsOrgRouteRoute._addFileChildren(
    protectedSettingsOrgRouteRouteChildren,
  )

interface protectedSettingsOrganizationRouteRouteChildren {
  protectedSettingsOrganizationMembersRoute: typeof protectedSettingsOrganizationMembersRoute
  protectedSettingsOrganizationTeamsRoute: typeof protectedSettingsOrganizationTeamsRoute
  protectedSettingsOrganizationIndexRoute: typeof protectedSettingsOrganizationIndexRoute
}

const protectedSettingsOrganizationRouteRouteChildren: protectedSettingsOrganizationRouteRouteChildren =
  {
    protectedSettingsOrganizationMembersRoute:
      protectedSettingsOrganizationMembersRoute,
    protectedSettingsOrganizationTeamsRoute:
      protectedSettingsOrganizationTeamsRoute,
    protectedSettingsOrganizationIndexRoute:
      protectedSettingsOrganizationIndexRoute,
  }

const protectedSettingsOrganizationRouteRouteWithChildren =
  protectedSettingsOrganizationRouteRoute._addFileChildren(
    protectedSettingsOrganizationRouteRouteChildren,
  )

interface protectedSettingsRouteRouteChildren {
  protectedSettingsOrgRouteRoute: typeof protectedSettingsOrgRouteRouteWithChildren
  protectedSettingsOrganizationRouteRoute: typeof protectedSettingsOrganizationRouteRouteWithChildren
  protectedSettingsIndexRoute: typeof protectedSettingsIndexRoute
}

const protectedSettingsRouteRouteChildren: protectedSettingsRouteRouteChildren =
  {
    protectedSettingsOrgRouteRoute: protectedSettingsOrgRouteRouteWithChildren,
    protectedSettingsOrganizationRouteRoute:
      protectedSettingsOrganizationRouteRouteWithChildren,
    protectedSettingsIndexRoute: protectedSettingsIndexRoute,
  }

const protectedSettingsRouteRouteWithChildren =
  protectedSettingsRouteRoute._addFileChildren(
    protectedSettingsRouteRouteChildren,
  )

interface protectedRouteRouteChildren {
  protectedChatsRouteRoute: typeof protectedChatsRouteRouteWithChildren
  protectedSettingsRouteRoute: typeof protectedSettingsRouteRouteWithChildren
  protectedDashboardRoute: typeof protectedDashboardRoute
}

const protectedRouteRouteChildren: protectedRouteRouteChildren = {
  protectedChatsRouteRoute: protectedChatsRouteRouteWithChildren,
  protectedSettingsRouteRoute: protectedSettingsRouteRouteWithChildren,
  protectedDashboardRoute: protectedDashboardRoute,
}

const protectedRouteRouteWithChildren = protectedRouteRoute._addFileChildren(
  protectedRouteRouteChildren,
)

interface publicDocsRouteRouteChildren {
  publicDocsSplatRoute: typeof publicDocsSplatRoute
}

const publicDocsRouteRouteChildren: publicDocsRouteRouteChildren = {
  publicDocsSplatRoute: publicDocsSplatRoute,
}

const publicDocsRouteRouteWithChildren = publicDocsRouteRoute._addFileChildren(
  publicDocsRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicDocsRouteRoute: typeof publicDocsRouteRouteWithChildren
  publicAuthRoute: typeof publicAuthRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicDocsRouteRoute: publicDocsRouteRouteWithChildren,
  publicAuthRoute: publicAuthRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  protectedRouteRoute: protectedRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  ApiModelsRoute: ApiModelsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
